Repository cesko-digital/covid.gov.cz, pull requests merged in 2020-10, with the labels that each got.

#7 README updated, LICENSE and CONTRIBUTING removed from frontend
  README.md
  gatsby/CONTRIBUTING.md
  gatsby/LICENSE.md
  gatsby/README.md
Labels: documentation

#17 refactor(design system): cleaner global css import
  gatsby/config/gatsby-browser.tsx
  gatsby/config/gatsby-ssr.tsx
  gatsby/src/components/hello/hello.tsx
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/pages/index.tsx
Labels: enhancement

#19 gatsby: footer & link component
  gatsby/config/gatsby-browser.tsx
  gatsby/config/gatsby-config.ts
  gatsby/config/gatsby-ssr.tsx
  gatsby/package.json
  gatsby/src/components/footer/footer.tsx
  gatsby/src/components/footer/index.tsx
  gatsby/src/components/link/index.tsx
  gatsby/src/components/link/link.tsx
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/pages/index.tsx
  gatsby/yarn.lock
Labels: enhancement

#23 feat(FE): button component
  .vscode/settings.json
  gatsby/package.json
  gatsby/src/components/button/button.tsx
  gatsby/src/components/button/index.tsx
  gatsby/yarn.lock
Labels: enhancement

#9 gatsby: Jest setup
  .github/workflows/gatsby.yml
  gatsby/__mocks__/ react-i18next.js
  gatsby/__mocks__/file-mock.js
  gatsby/__mocks__/gatsby.js
  gatsby/jest-preprocess.js
  gatsby/jest.config.js
  gatsby/loadershim.js
  gatsby/package.json
  gatsby/setupTests.js
  gatsby/tsconfig.json
  gatsby/yarn.lock
Labels: enhancement

#18 introduce ApplicationInsight
  README.md
  gatsby/config/gatsby-browser.tsx
  gatsby/config/gatsby-config.ts
  gatsby/gatsby-config.js
  gatsby/package.json
  gatsby/src/hooks/useAnalytics.ts
  gatsby/src/types/global.d.ts
  gatsby/yarn.lock
Labels: enhancement

#24 feat(FE): Breadcrumb nav component
  gatsby/src/components/breadcrumb/breadcrumb.tsx
  gatsby/src/components/breadcrumb/index.tsx
Labels: enhancement

#25 fix gitignore files to see samples
  gatsby/.env.development.sample
  gatsby/.gitignore
Labels: bug

#29 Gatsby/fix/analytics mock
  gatsby/config/gatsby-browser.tsx
  gatsby/src/components/link/link.tsx
  gatsby/src/hooks/useAnalytics.ts
Labels: bug

#28 Bootstrap grid system added
  gatsby/src/components/col/col.tsx
  gatsby/src/components/col/index.tsx
  gatsby/src/components/container/container.tsx
  gatsby/src/components/container/index.tsx
  gatsby/src/components/row/index.tsx
  gatsby/src/components/row/row.tsx
Labels: enhancement

#31 feat(gov icons): gov icon component
  gatsby/src/components/gov-icon/gov-icon.tsx
  gatsby/src/components/gov-icon/index.tsx
Labels: enhancement

#32 fix(FE): added types for Helmet
  gatsby/package.json
  gatsby/yarn.lock
Labels: bug

#33 docs(readme): links added to README
  README.md
Labels: documentation
