Repository cesko-digital/covid.gov.cz, pull requests merged in 2020-11, with the labels that each got.

#30 fix(env): use app insights only in production
  README.md
  gatsby/.env.development.example
  gatsby/.env.production.example
  gatsby/config/gatsby-browser.tsx
  gatsby/src/adapters/analytics-adapter.ts
  gatsby/src/types/global.d.ts
Labels: bug

#27 gatsby: measure-list, content-box, text page
  gatsby/.eslintrc
  gatsby/src/components/button/button.tsx
  gatsby/src/components/button/index.tsx
  gatsby/src/components/content-box/content-box.module.scss
  gatsby/src/components/content-box/content-box.module.scss.d.ts
  gatsby/src/components/content-box/content-box.tsx
  gatsby/src/components/content-box/index.tsx
  gatsby/src/components/headline/headline.module.scss
  gatsby/src/components/headline/headline.module.scss.d.ts
  gatsby/src/components/headline/headline.tsx
  gatsby/src/components/headline/index.tsx
  gatsby/src/components/measure-list/index.tsx
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/components/measure-list/measure.module.scss
  gatsby/src/components/measure-list/measure.module.scss.d.ts
  gatsby/src/components/measure-list/measure.tsx
  gatsby/src/components/text-box/index.tsx
  gatsby/src/components/text-box/text-box.module.scss
  gatsby/src/components/text-box/text-box.module.scss.d.ts
  gatsby/src/components/text-box/text-box.tsx
  gatsby/src/layouts/default-layout.module.scss
  gatsby/src/layouts/default-layout.module.scss.d.ts
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/pages/index.tsx
  gatsby/src/pages/text.tsx
Labels: enhancement

#34 gatsby: listen on 0.0.0.0
  gatsby/package.json
Labels: enhancement

#35 feat(search box): search box component
  gatsby/src/components/button/button.tsx
  gatsby/src/components/gov-icon/gov-icon.tsx
  gatsby/src/components/search-box/index.tsx
  gatsby/src/components/search-box/search-box.tsx
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/pages/index.tsx
Labels: enhancement

#37 fix(gov icons): icon list fixed
  gatsby/src/components/gov-icon/gov-icon.tsx
Labels: bug

#39 Alert box added
  gatsby/assets/ds/scss/vendor/bootstrap/utilities/_text.scss
  gatsby/src/adapters/analytics.adapter.ts
  gatsby/src/components/alert/alert.tsx
  gatsby/src/components/alert/index.tsx
  gatsby/src/components/button/button.tsx
  gatsby/src/pages/index.tsx
Labels: enhancement

#36 gatsby: rewrite container, fix margins on boxes
  gatsby/assets/ds/scss/base/_variables.scss
  gatsby/src/components/content-box/content-box.module.scss
  gatsby/src/components/headline/headline.module.scss
  gatsby/src/components/text-box/text-box.module.scss
  gatsby/src/pages/text.tsx
Labels: bug

#47 fix(purge css): config updated, classes added to comments
  gatsby/config/gatsby-config.ts
  gatsby/src/components/container/container.tsx
Labels: bug

#62 gatsby: Alert box update + test
  gatsby/jest.config.js
  gatsby/locales/cs/translation.json
  gatsby/locales/en/translation.json
  gatsby/package.json
  gatsby/src/components/alert/alert-container.tsx
  gatsby/src/components/alert/alert.tsx
  gatsby/src/components/alert/index.tsx
  gatsby/src/components/button/button.tsx
  gatsby/src/components/button/variants.module.scss
  gatsby/src/components/button/variants.module.scss.d.ts
  gatsby/src/pages/index.tsx
  gatsby/src/tests/__snapshots__/alert.react.test.tsx.snap
  gatsby/src/tests/alert.react.test.tsx
  gatsby/yarn.lock
Labels: enhancement

#63 fix(alert): button class fixed
  gatsby/config/gatsby-config.ts
  gatsby/src/components/button/button.tsx
  gatsby/src/components/button/variants.module.scss
  gatsby/src/components/button/variants.module.scss.d.ts
  gatsby/src/tests/__snapshots__/alert.react.test.tsx.snap
  gatsby/src/tests/alert.react.test.tsx
Labels: bug

#61 feat(graphql-types): added type generator
  gatsby/.eslintignore
  gatsby/.gitignore
  gatsby/config/gatsby-config.ts
  gatsby/package.json
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/pages/index.tsx
  gatsby/yarn.lock
Labels: enhancement

#69 Drupal: mssql multiple fixes and adding missing files.
  docker/.env.example
  docker/Dockerfile.php
  docker/docker-compose.yml
  drupal/.gitignore
  drupal/composer.json
  drupal/web/sites/default/settings.php
Labels: Drupal

#72 Drupal: Add password policy.
  drupal/composer.json
  drupal/composer.lock
  drupal/config/sync/core.entity_form_display.user.user.default.yml
  drupal/config/sync/core.extension.yml
  drupal/config/sync/field.field.user.user.field_last_password_reset.yml
  drupal/config/sync/field.field.user.user.field_password_expiration.yml
  drupal/config/sync/field.storage.user.field_last_password_reset.yml
  drupal/config/sync/field.storage.user.field_password_expiration.yml
  drupal/config/sync/language/en/field.field.user.user.field_last_password_reset.yml
  drupal/config/sync/language/en/field.field.user.user.field_password_expiration.yml
  drupal/config/sync/password_policy.password_policy.nakit.yml
  drupal/config/sync/password_policy.settings.yml
Labels: Drupal

#77 fix(workflows): remove caching from ci/cd
  .github/workflows/gatsby.yml
Labels: bug

#85 fix(FE): index gql query
  gatsby/config/gatsby-config.ts
  gatsby/src/pages/index.tsx
Labels: bug

#87 fix(workflows): fixed frontend workflow
  .github/workflows/gatsby.yml
  gatsby/.env.production.example
  gatsby/.stylelintrc
Labels: bug

#90 fix(FE): added measures to index gql query
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/hooks/useMobile.ts
  gatsby/src/pages/index.tsx
Labels: bug

#91 fix(measure list): remove debug text
  gatsby/src/components/measure-list/measure-list.tsx
Labels: bug

#86 test(gatsby): add unit tests for button, column and row
  gatsby/__tests__/__snapshots__/button.react.test.tsx.snap
  gatsby/__tests__/__snapshots__/column.react.test.tsx.snap
  gatsby/__tests__/__snapshots__/row.react.test.tsx.snap
  gatsby/__tests__/button.react.test.tsx
  gatsby/__tests__/column.react.test.tsx
  gatsby/__tests__/row.react.test.tsx
Labels: enhancement

#89 Gatsby/feature/basic situations
  gatsby/config/create-pages.ts
  gatsby/config/gatsby-config.ts
  gatsby/config/gatsby-node.ts
  gatsby/src/components/button/index.tsx
  gatsby/src/components/header/header.tsx
  gatsby/src/components/header/index.tsx
  gatsby/src/components/link/link.tsx
  gatsby/src/components/list-card/index.tsx
  gatsby/src/components/list-card/list-card.tsx
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/components/situations-box/situation.tsx
  gatsby/src/components/situations-box/situations-box.tsx
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/pages/index.tsx
  gatsby/src/templates/situation/list.tsx
  gatsby/src/templates/situation/page.tsx
Labels: enhancement

#93 Drupal: Add group for container user.
  docker/Dockerfile.azure
Labels: Drupal

#55 Gatsby: header component
  gatsby/config/gatsby-browser.tsx
  gatsby/src/components/gov-icon/gov-icon.tsx
  gatsby/src/components/header/header-locale-select.module.scss
  gatsby/src/components/header/header-locale-select.module.scss.d.ts
  gatsby/src/components/header/header-locale-select.tsx
  gatsby/src/components/header/header-logo.svg
  gatsby/src/components/header/header.module.scss
  gatsby/src/components/header/header.module.scss.d.ts
  gatsby/src/components/header/header.tsx
  gatsby/src/components/header/index.ts
  gatsby/src/components/search-box/search-box.module.scss
  gatsby/src/components/search-box/search-box.module.scss.d.ts
  gatsby/src/components/search-box/search-box.tsx
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/pages/index.tsx
  gatsby/src/types/image-files.d.ts
Labels: enhancement

#97 Gatsby: fix AlertContainer typo
  gatsby/src/components/alert/alert-container.tsx
  gatsby/src/components/alert/index.tsx
Labels: bug

#95 Drupal: Add custom block type Content.
  drupal/config/sync/block_content.type.basic_content.yml
  drupal/config/sync/core.entity_form_display.block_content.basic_content.default.yml
  drupal/config/sync/core.entity_view_display.block_content.basic_content.default.yml
  drupal/config/sync/core.entity_view_mode.block_content.full.yml
  drupal/config/sync/core.extension.yml
  drupal/config/sync/editor.editor.basic.yml
  drupal/config/sync/field.field.block_content.basic_content.field_b_content.yml
  drupal/config/sync/field.storage.block_content.body.yml
  drupal/config/sync/field.storage.block_content.field_b_content.yml
  drupal/config/sync/filter.format.basic.yml
  drupal/config/sync/jsonapi_extras.jsonapi_resource_config.block_content--basic_content.yml
  drupal/config/sync/language.content_settings.block_content.basic_content.yml
  drupal/config/sync/language/en/core.entity_view_mode.block_content.full.yml
  drupal/config/sync/language/en/views.view.block_content.yml
  drupal/config/sync/views.view.block_content.yml
Labels: Drupal

#98 Gatsby: fix btn-small-black style, add hover
  gatsby/src/components/button/variants.module.scss
Labels: enhancement

#96 Gatsby: Add missing links to detail (measures, situations)
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/components/measure-list/measure.tsx
  gatsby/src/components/situations-box/situation.module.scss
  gatsby/src/components/situations-box/situation.tsx
  gatsby/src/pages/index.tsx
Labels: enhancement

#108 Drupal: fix translations
  drupal/web/modules/custom/covid/src/Entity/Translation.php
  drupal/web/modules/custom/covid_ui/src/Form/AddTranslationForm.php
Labels: bug

#117 Drupal: translation json api fix
  drupal/config/sync/jsonapi_extras.jsonapi_resource_config.covid_translation--covid_translation.yml
Labels: bug

#115 Gatsby: SearchBoxInput: add padding right
  gatsby/src/components/search-box/search-box.module.scss
Labels: bug

#123 Drupal: area icon
  drupal/config/sync/core.entity_form_display.taxonomy_term.area.default.yml
  drupal/config/sync/core.entity_view_display.taxonomy_term.area.default.yml
  drupal/config/sync/field.field.taxonomy_term.area.field_ref_icon.yml
  drupal/config/sync/field.storage.taxonomy_term.field_ref_icon.yml
Labels: enhancement

#128 feat: added custom pages logic, added 404 page
  gatsby/config/create-pages.ts
  gatsby/config/gatsby-config.ts
  gatsby/src/pages/404.module.scss
  gatsby/src/pages/404.module.scss.d.ts
  gatsby/src/pages/404.tsx
  gatsby/src/templates/custom-page/custom-page.tsx
Labels: enhancement

#116 Gatsby: situation detial: replace new line by <br>
  gatsby/src/components/situation-detail/situation-detail.tsx
Labels: bug

#125 Fix Actual Limitations Butttons
  gatsby/src/components/button/button.tsx
  gatsby/src/components/measure-list/measure.tsx
Labels: bug

#114 Gatsby: change favicon
  gatsby/config/gatsby-config.ts
  gatsby/package.json
  gatsby/static/favicon.ico
  gatsby/static/favicon.svg
  gatsby/yarn.lock
Labels: enhancement

#120 Introduce FAQ accordion
  gatsby/src/components/accordion/accordion-item.module.scss
  gatsby/src/components/accordion/accordion-item.module.scss.d.ts
  gatsby/src/components/accordion/accordion-item.tsx
  gatsby/src/components/accordion/accordion-section.module.scss
  gatsby/src/components/accordion/accordion-section.module.scss.d.ts
  gatsby/src/components/accordion/accordion-section.tsx
  gatsby/src/components/accordion/accordion.tsx
  gatsby/src/components/bolded-title/bolded-title.module.scss
  gatsby/src/components/bolded-title/bolded-title.module.scss.d.ts
  gatsby/src/components/bolded-title/index.tsx
  gatsby/src/components/content-box/content-box.module.scss
  gatsby/src/components/content-box/content-box.module.scss.d.ts
  gatsby/src/components/content-box/content-box.tsx
  gatsby/src/components/situation-detail/situation-detail.tsx
  gatsby/src/pages/text.tsx
Labels: enhancement

#124 Gatsby: Add content translations from Drupal.
  gatsby/config/gatsby-config.ts
  gatsby/gatsby-source-drupal/.Rhistory
  gatsby/gatsby-source-drupal/.babelrc
  gatsby/gatsby-source-drupal/CHANGELOG.md
  gatsby/gatsby-source-drupal/LICENSE
  gatsby/gatsby-source-drupal/README.md
  gatsby/gatsby-source-drupal/gatsby-node.js
  gatsby/gatsby-source-drupal/index.js
  gatsby/gatsby-source-drupal/normalize.js
  gatsby/gatsby-source-drupal/package.json
  gatsby/gatsby-source-drupal/utils.js
  gatsby/package.json
Labels: enhancement

#127 feat(pagination): pagination added
  gatsby/src/components/pagination/index.tsx
  gatsby/src/components/pagination/pagination-button.module.scss
  gatsby/src/components/pagination/pagination-button.module.scss.d.ts
  gatsby/src/components/pagination/pagination-button.tsx
  gatsby/src/components/pagination/pagination.module.scss
  gatsby/src/components/pagination/pagination.module.scss.d.ts
  gatsby/src/components/pagination/pagination.tsx
Labels: enhancement

#137 Drupal: Enable Vietnamese language.
  drupal/config/sync/language.entity.und.yml
  drupal/config/sync/language.entity.vi.yml
  drupal/config/sync/language.entity.zxx.yml
  drupal/config/sync/language.negotiation.yml
  drupal/config/sync/language/vi/block.block.adminimal_theme_content.yml
  drupal/config/sync/language/vi/block.block.adminimal_theme_login.yml
  drupal/config/sync/language/vi/block.block.adminimal_theme_page_title.yml
  drupal/config/sync/language/vi/block.block.adminimal_theme_primary_local_tasks.yml
  drupal/config/sync/language/vi/block.block.adminimal_theme_secondary_local_tasks.yml
  drupal/config/sync/language/vi/block.block.covid_admin_content.yml
  drupal/config/sync/language/vi/block.block.covid_admin_login.yml
  drupal/config/sync/language/vi/block.block.covid_admin_page_title.yml
  drupal/config/sync/language/vi/block.block.covid_admin_primary_local_tasks.yml
  drupal/config/sync/language/vi/block.block.covid_admin_secondary_local_tasks.yml
  drupal/config/sync/language/vi/core.entity_form_mode.user.register.yml
  drupal/config/sync/language/vi/core.entity_view_mode.block_content.full.yml
  drupal/config/sync/language/vi/core.entity_view_mode.node.full.yml
  drupal/config/sync/language/vi/core.entity_view_mode.node.rss.yml
  drupal/config/sync/language/vi/core.entity_view_mode.node.search_index.yml
  drupal/config/sync/language/vi/core.entity_view_mode.node.teaser.yml
  drupal/config/sync/language/vi/core.entity_view_mode.taxonomy_term.full.yml
  drupal/config/sync/language/vi/core.entity_view_mode.user.full.yml
  drupal/config/sync/language/vi/filter.format.plain_text.yml
  drupal/config/sync/language/vi/language.entity.en.yml
  drupal/config/sync/language/vi/system.action.node_make_sticky_action.yml
  drupal/config/sync/language/vi/system.action.node_make_unsticky_action.yml
  drupal/config/sync/language/vi/system.action.node_promote_action.yml
  drupal/config/sync/language/vi/system.action.node_publish_action.yml
  drupal/config/sync/language/vi/system.action.node_save_action.yml
  drupal/config/sync/language/vi/system.action.node_unpromote_action.yml
  drupal/config/sync/language/vi/system.action.node_unpublish_action.yml
  drupal/config/sync/language/vi/system.action.pathauto_update_alias_node.yml
  drupal/config/sync/language/vi/system.action.pathauto_update_alias_user.yml
  drupal/config/sync/language/vi/system.maintenance.yml
  drupal/config/sync/language/vi/system.menu.admin.yml
  drupal/config/sync/language/vi/system.menu.devel.yml
  drupal/config/sync/language/vi/system.menu.footer.yml
  drupal/config/sync/language/vi/system.menu.tools.yml
  drupal/config/sync/language/vi/user.mail.yml
  drupal/config/sync/language/vi/user.role.anonymous.yml
  drupal/config/sync/language/vi/user.settings.yml
  drupal/config/sync/language/vi/views.view.archive.yml
  drupal/config/sync/language/vi/views.view.block_content.yml
  drupal/config/sync/language/vi/views.view.content.yml
  drupal/config/sync/language/vi/views.view.content_recent.yml
  drupal/config/sync/language/vi/views.view.files.yml
  drupal/config/sync/language/vi/views.view.frontpage.yml
  drupal/config/sync/language/vi/views.view.glossary.yml
  drupal/config/sync/language/vi/views.view.moderated_content.yml
  drupal/config/sync/language/vi/views.view.taxonomy_term.yml
  drupal/config/sync/language/vi/views.view.user_admin_people.yml
  drupal/config/sync/language/vi/views.view.watchdog.yml
  drupal/config/sync/language/vi/views.view.who_s_new.yml
  drupal/config/sync/language/vi/views.view.who_s_online.yml
Labels: Drupal

#140 feat(ga): added google analytics
  gatsby/config/gatsby-config.ts
  gatsby/package.json
  gatsby/yarn.lock
Labels: enhancement

#148 Drupal: change section labels on homepage to formatted
  drupal/config/sync/core.entity_form_display.node.homepage.default.yml
  drupal/config/sync/core.entity_view_display.node.homepage.default.yml
  drupal/config/sync/core.entity_view_display.node.homepage.teaser.yml
  drupal/config/sync/field.field.node.homepage.field_f_hp_measure_label.yml
  drupal/config/sync/field.field.node.homepage.field_f_hp_situation_label.yml
  drupal/config/sync/field.storage.node.field_f_hp_measure_label.yml
  drupal/config/sync/field.storage.node.field_f_hp_situation_label.yml
  drupal/config/sync/field.storage.node.field_hp_measure_label.yml
  drupal/config/sync/field.storage.node.field_hp_situation_label.yml
  drupal/config/sync/jsonapi_extras.jsonapi_resource_config.node--homepage.yml
Labels: Drupal

#169 fix(breadcrumb): no wrap always show
  gatsby/src/components/breadcrumb/breadcrumb.module.scss
  gatsby/src/components/breadcrumb/breadcrumb.module.scss.d.ts
  gatsby/src/components/breadcrumb/breadcrumb.tsx
Labels: bug

#180 Gatsby: homepage measures fixes
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/components/measure-list/measure.tsx
  gatsby/src/templates/lists/index.tsx
Labels: bug

#190 Gatsby: add breadcrumb active color
  gatsby/src/components/breadcrumb/breadcrumb.module.scss
  gatsby/src/components/breadcrumb/breadcrumb.module.scss.d.ts
  gatsby/src/components/breadcrumb/breadcrumb.tsx
Labels: bug, enhancement

#191 Gatsby: hotfix detail without links
  gatsby/src/components/situation-detail/situation-detail.tsx
Labels: bug

#205 fix: files with code check errors fixed
  gatsby/src/components/header/header-locale-select.tsx
  gatsby/src/components/header/header.tsx
  gatsby/src/components/i18n/i18n.tsx
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/templates/custom-page/custom-page.tsx
Labels: bug

#202 [WIP] feat(guide): guide added
  gatsby/assets/scss/design-system/base/_mixins.scss
  gatsby/assets/scss/design-system/base/_variables.scss
  gatsby/config/gatsby-config.ts
  gatsby/src/components/button/button.tsx
  gatsby/src/components/guide/guide-item.module.scss
  gatsby/src/components/guide/guide-item.module.scss.d.ts
  gatsby/src/components/guide/guide-item.tsx
  gatsby/src/components/guide/guide.module.scss
  gatsby/src/components/guide/guide.module.scss.d.ts
  gatsby/src/components/guide/guide.tsx
  gatsby/src/components/guide/index.tsx
  gatsby/src/components/i18n/i18n.tsx
  gatsby/src/components/measure-list/measure-list.tsx
  gatsby/src/templates/lists/index.tsx
  gatsby/static/images/main-bg_1920px.jpg
Labels: enhancement

#208 fix: photo
  gatsby/static/images/main-bg_1920px.jpg
Labels: bug

#211 feat(desktop-index): enhancement
  gatsby/src/components/desktop-top-content/desktop-top-content.module.scss
  gatsby/src/components/desktop-top-content/desktop-top-content.module.scss.d.ts
  gatsby/src/components/desktop-top-content/desktop-top-content.tsx
  gatsby/src/components/desktop-top-content/index.tsx
  gatsby/src/components/main-background/main-background.tsx
  gatsby/src/hooks/useMobile.ts
  gatsby/src/layouts/default-layout.tsx
  gatsby/src/templates/lists/index.tsx
Labels: enhancement

#218 feat(index): button colours, header
  gatsby/src/components/content-box/content-box.module.scss
  gatsby/src/components/content-box/content-box.module.scss.d.ts
  gatsby/src/components/content-box/content-box.tsx
  gatsby/src/components/desktop-top-content/desktop-top-content.module.scss
  gatsby/src/components/desktop-top-content/desktop-top-content.tsx
  gatsby/src/components/guide/guide-item.module.scss
  gatsby/src/components/guide/guide-item.tsx
  gatsby/src/components/guide/guide.module.scss
  gatsby/src/components/guide/guide.tsx
  gatsby/src/components/measure-list/measure.module.scss
  gatsby/src/components/measure-list/measure.tsx
  gatsby/src/components/situations-box/situations-box.tsx
  gatsby/src/templates/lists/index.tsx
Labels: bug, enhancement

#231 feat(navbar): gradient design
  gatsby/src/components/header/header.module.scss
  gatsby/src/components/header/header.module.scss.d.ts
  gatsby/src/components/header/header.tsx
  gatsby/src/layouts/default-layout.module.scss
  gatsby/src/layouts/default-layout.module.scss.d.ts
  gatsby/src/layouts/default-layout.tsx
Labels: enhancement

#234 fix(mobile menu): fix
  gatsby/src/components/footer/footer.module.scss
  gatsby/src/components/header/header.module.scss
  gatsby/src/components/header/header.tsx
  gatsby/src/templates/lists/index.tsx
Labels: bug

#260 Ops: Run pipeline every two hours.
  .github/workflows/deploy.yml
Labels: Drupal

#266 Fix in pipelines and Drupal config cleanup.
  .github/workflows/deploy.yml
  drupal/config/sync/core.entity_form_display.node.page.default.yml
  drupal/config/sync/core.entity_form_display.taxonomy_term.icons.default.yml
  drupal/config/sync/core.entity_form_display.user.user.default.yml
Labels: Drupal

#267 Drupal: Forbid content deleting.
  drupal/web/modules/custom/covid/covid.module
Labels: Drupal

#269 Drupal: Rename File API resource.
  drupal/config/sync/jsonapi_extras.jsonapi_resource_config.file--file.yml
  gatsby/config/gatsby-config.ts
Labels: Drupal

#270 Drupal: Add better native spellchecker.
  drupal/web/modules/custom/covid/covid.module
Labels: Drupal

#277 Drupal: Update README.
  README.md
Labels: Drupal

#279 Drupal: Enable editor with option to change URL alias.
  drupal/config/sync/language.negotiation.yml
  drupal/config/sync/user.role.editor.yml
  drupal/config/sync/user.role.reviewer.yml
Labels: Drupal

#282 Drupal: Sticky header for translations table.
  drupal/web/modules/custom/covid_ui/src/Form/TranslateForm.php
Labels: Drupal

#295 Drupal: Replace regular spaces with non-breakable.
  drupal/web/modules/custom/covid/src/Normalizer.php
Labels: Drupal

#290 Drupal: Remove migrate code.
  drupal/config/sync/core.extension.yml
  drupal/config/sync/jsonapi_extras.jsonapi_resource_config.migration--migration.yml
  drupal/config/sync/jsonapi_extras.jsonapi_resource_config.migration_group--migration_group.yml
  drupal/config/sync/migrate_plus.migration.categories.yml
  drupal/config/sync/migrate_plus.migration.measures.yml
  drupal/config/sync/migrate_plus.migration.situations.yml
  drupal/config/sync/migrate_plus.migration.term_icons.yml
  drupal/config/sync/migrate_plus.migration_group.covid.yml
  drupal/web/modules/custom/covid/src/Plugin/migrate/process/FileImport.php
Labels: Drupal

#307 Drupal/feature/normalize
  drupal/web/modules/custom/covid/covid.services.yml
  drupal/web/modules/custom/covid/src/Normalizer/Normalizer.php
  drupal/web/modules/custom/covid/src/Normalizer/TextProcessedNormalizer.php
Labels: Drupal

#324 Drupal: Editors should be able to archive content.
  drupal/config/sync/user.role.editor.yml
  drupal/config/sync/user.role.reviewer.yml
Labels: Drupal

#329 gatsby/fix: loading fonts from google fonts instead of static folder
  gatsby/assets/fonts/roboto-bold.woff2
  gatsby/assets/fonts/roboto-regular.woff2
  gatsby/assets/scss/design-system/base/_typography.scss
  gatsby/config/gatsby-config.ts
  gatsby/src/layouts/default-layout.tsx
  gatsby/static/fonts/roboto/roboto-bold.ttf
  gatsby/static/fonts/roboto/roboto-bold.woff
  gatsby/static/fonts/roboto/roboto-light.ttf
  gatsby/static/fonts/roboto/roboto-light.woff
  gatsby/static/fonts/roboto/roboto-medium.ttf
  gatsby/static/fonts/roboto/roboto-medium.woff
  gatsby/static/fonts/roboto/roboto-regular.ttf
  gatsby/static/fonts/roboto/roboto-regular.woff
  gatsby/static/fonts/roboto/roboto-thin.ttf
  gatsby/static/fonts/roboto/roboto-thin.woff
Labels: bug, enhancement

#350 Drupal enable strict workflow
  drupal/config/sync/user.role.editor.yml
  drupal/config/sync/user.role.translator.yml
  drupal/config/sync/user.role.user_manager.yml
  drupal/config/sync/workflows.workflow.content.yml
Labels: Drupal

#361 Drupal: Fix MFA login
  drupal/config/sync/user.role.authenticated.yml
Labels: Drupal

#360 feat: last updated label
  gatsby/assets/scss/design-system/base/_variables.scss
  gatsby/src/components/last-update/index.ts
  gatsby/src/components/last-update/last-update.module.scss
  gatsby/src/components/last-update/last-update.module.scss.d.ts
  gatsby/src/components/last-update/last-update.tsx
  gatsby/src/components/measure-detail/measure-detail.tsx
  gatsby/src/components/situation-detail/situation-detail.tsx
  gatsby/src/components/topic-detail/topic-detail.tsx
Labels: enhancement

#392 Drupal: Add Q&A for PES.
  drupal/config/sync/core.entity_form_display.paragraph.pes_content.default.yml
  drupal/config/sync/core.entity_view_display.paragraph.pes_content.default.yml
  drupal/config/sync/field.field.paragraph.pes_content.field_qa.yml
  drupal/config/sync/field.storage.paragraph.field_qa.yml
Labels: Drupal

#395 Drupal: Force users to agree with license agreement.
  drupal/.gitignore
  drupal/web/.gitignore
  drupal/web/modules/custom/covid/covid.routing.yml
  drupal/web/modules/custom/covid/covid.services.yml
  drupal/web/modules/custom/covid/src/EventSubscriber/RequestEventSubscriber.php
  drupal/web/modules/custom/covid/src/Form/LicenseAgreementForm.php
  drupal/web/themes/custom/covid_admin/css/covid_admin.css
  drupal/web/themes/custom/covid_admin/css/covid_admin.css.map
  drupal/web/themes/custom/covid_admin/css/covid_admin.scss
  drupal/web/themes/custom/covid_theme/css/.sass-cache/55d438618dee2784ffd0d7b3fe8d3f0a6acee975/styles.scssc
  drupal/web/themes/custom/covid_theme/css/.sass-cache/970549bad4788d725b4f05716cce06d71ceb7601/styles.scssc
Labels: Drupal
